### ISSUE TITLE
Does not rename file to include TV Show title

### ISSUE THREAD

**Issue by MDE186** [j4ym0/nextcloud-tv-show-namer#1]
Hi,

Thanks for the hard work in creating this.

It seems, and I don't know if this is planned, but it does not rename the files to include the TV Show title.

i.e. _TV Show Title_ - S01E01 - Show Title.mkv

Could this be added? Any advice.

Dont worry - You can close if required. Just added $title to Files.php

**Comment by j4ym0** [comment]
Thanks for the comment.

It is planned for an option to design your own file name from an option in settings.

if you have any comments on the below let me know.
![image](https://user-images.githubusercontent.com/8805526/134949231-3b156623-056b-4415-a8f4-a952403f243c.png)

**Comment by j4ym0** [comment]
#2
