### ISSUE TITLE
i18n: Context needed

### ISSUE THREAD

**Issue by rakekniven** [j4ym0/nextcloud-tv-show-namer#11]
https://github.com/j4ym0/nextcloud-tv-show-namer/blob/dc4ff9d9d20903b0d30b7c592ada01bcc2f0fefe/templates/content/index.php#L3

What does "Hang tight" means here?

Does it mean something like "Please wait …"?

**Comment by j4ym0** [comment]
Yes “Hang tight” is like saying “Please wait” “Please Hold” “Loading”

In UK English this is a slang saying.

From: ***@***.***>
Sent: 17 October 2022 17:34
To: ***@***.***>
Cc: ***@***.***>
Subject: [j4ym0/nextcloud-tv-show-namer] l18n: Context needed (Issue #11)


https://github.com/j4ym0/nextcloud-tv-show-namer/blob/dc4ff9d9d20903b0d30b7c592ada01bcc2f0fefe/templates/content/index.php#L3

What does "Hang tight" means here?

Does it mean something like "Please wait …"?

**Comment by rakekniven** [comment]
Hello, thanks for your quick reply.

Would it be ok for you to change it to "Please wait …"?

**Comment by j4ym0** [comment]
I sure can if it makes translation easier
________________________________

**Comment by rakekniven** [comment]
It is more common for the nextcloud project.
Should I provide an PR?

**Comment by j4ym0** [comment]
done. will release be released in a few days.
