### ISSUE TITLE
no files after "scan folder"

### ISSUE THREAD

**Issue by wuppiwuppi** [j4ym0/nextcloud-tv-show-namer#12]
It does not recognize any files in my "Scan folder" Selection

Nextcloud: 25.0.1
it is an "external storage" -> local linux file system. Opening the directory in nextcloud shows the files. File endings are mostly mkv.

Also: Should I scan a directory with only one tv-show or can I scan the directory containing all my shows?

**Comment by j4ym0** [comment]
I will look into your issue.

You should scan a folder named as the TV show, this folder should contain more folders with season 1 etc or all the files for that show.
It is not supported to scan the folder containing all you TV shows as only one show can be scanned at a time
________________________________
From: wuppiwuppi ***@***.***>
Sent: Tuesday, November 15, 2022 9:54:19 AM
To: j4ym0/nextcloud-tv-show-namer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [j4ym0/nextcloud-tv-show-namer] no files after "scan folder" (Issue #12)


It does not recognize any files in my "Scan folder" Selection

Nextcloud: 25.0.1
it is an "external storage" -> local linux file system. Opening the directory in nextcloud shows the files. File endings are mostly mkv.

Also: Should I scan a directory with only one tv-show or can I scan the directory containing all my shows?

**Comment by j4ym0** [comment]
After testing "external storage" dir on a local linux file system. It did work for me.

Please make sure your folder you are naming is called the TV Show title. 

@wuppiwuppi if you could send over the dir structure and a sample file name i can do some more testing for you. But using a external storage folder did return results for me here on all 25.0.[0-5]

**Comment by wuppiwuppi** [comment]
Hello, 

testing wise it looks like this:
lala@lala:/mnt/3tb/_Test$ tree
.
├── Alpha House
│   └── Season1
│       ├── Alpha.House.S01E01.480p.mkv
│       ├── Alpha.House.S01E02.480p.mkv
│       ├── Alpha.House.S01E03.480p.mkv
│       ├── Alpha.House.S01E04.480p.mkv
│       ├── Alpha.House.S01E05.480p.mkv
│       ├── Alpha.House.S01E06.480p.mkv
│       ├── Alpha.House.S01E07.480p.mkv
│       └── Alpha.House.S01E08.480p.mkv
└── Breeders 2020
    ├── Breeders.S01E01.720p.mkv
    ├── Breeders.S01E02.720p.mkv
    └── Breeders.S01E03.720p.mkv

3 directories, 11 files

Regardless of which dir I choose to "Scan Folder" dialog - it will always show "no files". The files are visible in the files app.

**Comment by j4ym0** [comment]
![Screenshot](https://user-images.githubusercontent.com/8805526/202490850-64f9f3f4-f3df-462f-8891-1605b485860c.png)

@wuppiwuppi Can you confirm if the "no files" message you mean is the above. If so, then clicking choose would scan that folder. The scan folder dialog is a folder selector and will not show any files but will scan the folder/s, then list them after you click choose and the dir is scanned.

**Comment by wuppiwuppi** [comment]
I tried to click choose in any of these - but there are no results like shown in your screenshot. It stays empty. 

edit: undersood - that dialog should not show files. this was not obvious for me.

**Comment by wuppiwuppi** [comment]
erm logger shows this:
{"reqId":"someid","level":0,"time":"2022-11-17T16:02:28+00:00","remoteAddr":"xx","user":"xxxxx","app":"no app in context","method":"POST","url":"/index.php/apps/tvshownamer/scan","message":"Der angemeldete Benutzer muss ein Administrator sein"

=> user needs to be admin?

**Comment by j4ym0** [comment]
Perfect, thanks I have managed to recreate the issue.

The issue is because the user is not a member of the admin group. It is not limited to external storage. The issue is also there on the users own directory.

I will look into a work around.

Thank you for reporting!

**Comment by wuppiwuppi** [comment]
Now it tells me to enter my api key. Which I did. However it does not seem to save it. When I hit refresh (F5) the field is empty again.
