### ISSUE TITLE
Feature Request - Support Titles in other languages

### ISSUE THREAD

**Issue by HannesJo0139** [j4ym0/nextcloud-tv-show-namer#16]
Being able to select a certain language for show and episodes names would be awesome. Do you think there is a chance to get that? :)

**Comment by j4ym0** [comment]
could you please give me a example of how you see this working? do you mean a dropdown to select the name of a show in alternative language? do you mean the show is in a different language?

could you please give me a example of the name of the shown and a filename

**Comment by HannesJo0139** [comment]
Some series in my lib have German audio only. So I would like to have them named in German too. Having a dropdown like 'preferred language' in the settings tab would be awesome. You could propably try to load series data in that preferred language and use English as fallback.

Let's take Malcolm in the Middle for instance.
`Malcolm in the Middle - S01E02 - Red Dress` would become `Malcolm mittendrin - S01E02 - Lois sieht rot`

**Comment by j4ym0** [comment]
This should be possible. I will look at adding this as you have described.
