### ISSUE TITLE
Add a data source https://thetvdb.com/

### ISSUE THREAD

**Issue by u2597511** [j4ym0/nextcloud-tv-show-namer#20]
Please add this data source as well. Many TV shows on this resource appear faster and the translation is more complete. Getting information from both resources is much better.

https://thetvdb.com/api-information#documentation

**Comment by j4ym0** [comment]
How do you propose to select the data source? 
- by a dropdown in the settings (probably my preferred)
- automatically searching the other if unavailable in one
- have both sources displayed

Looking through there documentation there v3 API is being discontinued (at some point soon) and the v4 API is based on licensing and end user subscriptions of $11.99. Or that is what i understand.
https://support.thetvdb.com/kb/faq.php?id=62

Personally i don't believe that the paid option is the way to go. If the licensing issue and end user fee could be worked out i would look at adding in.

Please let me know your feedback.

**Comment by u2597511** [comment]
I propose to select the data provider as follows. List of possible sources (implemented and configured) in order of priority. The user can determine the priority of a particular source by swapping them. Requests for information about a specific series are made in descending order of priority until the requested information is received. Once information is received, no further questioning is carried out.

About licensing.
I wouldn't interfere with this process. Many have a license to access, many received as a prize for activity. But all this is optional. TMDB requires a key too. Yes, this key is not for money, but it is needed and can become paid at any time. Let users decide whether to receive keys for them or not. Try contacting TVDB developers directly; I think they have developer support programs. I've seen several free products online with embedded keys and the words "powered by TVDB".

![Снимок экрана 2023-10-07 235230](https://github.com/j4ym0/nextcloud-tv-show-namer/assets/146567089/7f03be5e-344d-48f1-9129-fa6a5764062e)
