### ISSUE TITLE
It Seems not work at all or just not support Chinese?

### ISSUE THREAD

**Issue by ricky0829** [j4ym0/nextcloud-tv-show-namer#4]
I've tried different eposides, but all displayed "Unable to find xxx", for example:
![image](https://user-images.githubusercontent.com/28993319/178702301-1b7df563-2ba1-4cb8-9fbc-50f5bddce058.png)

In TMDB it can be searched:
![image](https://user-images.githubusercontent.com/28993319/178702460-a3d92546-17e7-477a-8803-27c2c94c1fbc.png)

**Comment by j4ym0** [comment]
Chinese is currently not supported.

If you can list a title using the Chinese characters and also a couple of episodes in the original format and how they should be named I will certainly add the support.

**Comment by j4ym0** [comment]
https://en.wikipedia.org/wiki/Unnatural_(TV_series)
アンナチュラル

**Comment by j4ym0** [comment]
Tested with folder name "アンナチュラル"
![image](https://user-images.githubusercontent.com/8805526/202924765-27735e35-8843-4381-bca3-f3c3dacdb873.png)
![image](https://user-images.githubusercontent.com/8805526/202925109-cacaf8da-0de5-4b0f-970c-a59c811a3c93.png)

Season number is missing from your files "S01" or "s1"
