### ISSUE TITLE
Support localization

### ISSUE THREAD

**Issue by p-bo** [j4ym0/nextcloud-tv-show-namer#6]
Hello,
Would it be possible to follow instructions on:
https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html
...and make your app more accessible for non-English speakers please?

Thanks :-)

**Comment by j4ym0** [comment]
Yes, I will start work on this for you.

**Comment by rakekniven** [comment]
Already done, or?

Very nice.

**Comment by j4ym0** [comment]
> Already done, or?
> 
> Very nice.

Almost, just need to do some testing before packaging the release.

Thanks @rakekniven for the gramma fixes!

**Comment by p-bo** [comment]
Thanks @j4ym0  and @rakekniven , translations are in works / done already :-)

**Comment by j4ym0** [comment]
v0.3.0, released
